# Generated by Django 3.2.9 on 2021-12-27 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_details', models.TextField()),
                ('post_status', models.CharField(choices=[('1', 'active'), ('0', 'nonactive')], default=(1, 'active'), max_length=10)),
                ('post_view', models.IntegerField()),
                ('post_date', models.DateField(default=datetime.datetime(2021, 12, 27, 21, 21, 6, 363743))),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categories.categories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
