# Generated by Django 3.2.9 on 2021-12-27 19:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='postImage/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 27, 21, 40, 51, 63977)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_view',
            field=models.IntegerField(default=0),
        ),
    ]
