# Generated by Django 3.2.9 on 2021-12-28 20:02

import Posts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 22, 2, 15, 289330)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(upload_to=Posts.models.image_upload),
        ),
    ]
