# Generated by Django 3.2.9 on 2021-12-28 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_auto_20211229_0039'),
        ('Posts', '0010_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 39, 31, 614232)),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_details', models.CharField(max_length=200)),
                ('com_date', models.DateField(default=datetime.datetime(2021, 12, 29, 0, 39, 31, 615229))),
                ('com_status', models.CharField(choices=[('1', 'active'), ('0', 'nonactive')], default=(0, 'nonactive'), max_length=10)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.post')),
            ],
        ),
    ]
