# Generated by Django 3.2.9 on 2021-12-28 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_auto_20211229_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 40, 24, 44644)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 40, 24, 43649)),
        ),
    ]
