# Generated by Django 3.2.9 on 2021-12-28 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_auto_20211229_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 41, 43, 653824)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_details',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 41, 43, 653824)),
        ),
    ]
