# Generated by Django 3.2.9 on 2021-12-29 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0016_auto_20211229_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 57, 4, 81562)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 57, 4, 80563)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
