# Generated by Django 3.2.9 on 2021-12-29 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0017_auto_20211229_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 59, 2, 438346)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 59, 2, 437348)),
        ),
    ]
