# Generated by Django 3.2.9 on 2022-01-24 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0018_auto_20211229_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 24, 22, 10, 50, 510498)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 24, 22, 10, 50, 509500)),
        ),
    ]
