# Generated by Django 3.2.9 on 2021-12-28 20:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0009_alter_customer_user_date_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meg_details', models.TextField()),
                ('meg_status', models.CharField(choices=[('1', 'active'), ('0', 'nonactive')], default=('0', 'nonactive'), max_length=10)),
                ('meg_date', models.DateField(default=datetime.datetime(2021, 12, 28, 22, 2, 15, 288339))),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_date_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 22, 2, 15, 287335)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_img',
            field=models.ImageField(default='photo/265261750_2137137816444812_3009440320167266103_n.jpg', upload_to='photo/'),
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_details', models.TextField()),
                ('re_date', models.DateField(default=datetime.datetime(2021, 12, 28, 22, 2, 15, 288339))),
                ('meg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
