# Generated by Django 3.2.9 on 2021-12-28 21:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_auto_20211228_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='Cust_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_date_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 23, 10, 33, 16195)),
        ),
        migrations.AlterField(
            model_name='message',
            name='meg_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 23, 10, 33, 16195)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='re_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 23, 10, 33, 17194)),
        ),
    ]
