# Generated by Django 3.2.9 on 2021-12-28 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_auto_20211228_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='Cust_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_date_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 23, 12, 16, 72569)),
        ),
        migrations.AlterField(
            model_name='message',
            name='meg_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 23, 12, 16, 72569)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='re_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 23, 12, 16, 73533)),
        ),
    ]
