# Generated by Django 3.2.9 on 2021-12-28 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_auto_20211228_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_date_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 39, 31, 613236)),
        ),
        migrations.AlterField(
            model_name='message',
            name='meg_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 39, 31, 613236)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='re_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 0, 39, 31, 614232)),
        ),
    ]
