# Generated by Django 3.2.9 on 2021-12-29 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_auto_20211229_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_date_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 59, 2, 436351)),
        ),
        migrations.AlterField(
            model_name='message',
            name='meg_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 59, 2, 436351)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='re_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 59, 2, 436351)),
        ),
    ]
