# Generated by Django 3.2.9 on 2021-12-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
